# -*- coding: utf-8 -*-
"""DataPreprocessingEDAandFeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JqbIxMKKfJ3w2cXdgPgt4dBWq2j3MnnH
"""

!pip install -q ydata-profiling # Installed for generating the comprehensive final HTML report

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import io
import os
import ipywidgets as widgets
from IPython.display import display, clear_output, Markdown
from google.colab import files
from sklearn.preprocessing import StandardScaler, LabelEncoder, KBinsDiscretizer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold, RFE, SelectFromModel
from sklearn.decomposition import PCA
from ydata_profiling import ProfileReport

warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid")

# =====================================================================
# STEP 0: Generate README.md for GitHub
# =====================================================================
print("--- Step 0: Generating README.md ---")
readme_content = """# Automated EDA and Feature Engineering Pipeline

## Overview
This repository contains a reproducible, dynamic Python pipeline built in Google Colab that performs automated Exploratory Data Analysis (EDA) and Feature Engineering on any uploaded CSV dataset.

## Capabilities / Steps Performed
1. **Data Cleaning:** Automatically identifies and drops duplicates. Imputes missing numerical values with the median and categorical values with the mode. Outliers are handled dynamically via the Interquartile Range (IQR) capping method. A summary of these actions is provided in the output.
2. **Feature Engineering:** Scales numeric variables (StandardScaler), encodes categorical features (LabelEncoder), and generates binned categorical features for continuous data.
3. **Applied EDA:** Produces visual distributions and correlation heatmaps to extract data relationships.
4. **Feature Selection & Dimensionality Reduction (Comprehensive Narrative):**
   - **Feature Selection:** To avoid the curse of dimensionality and remove noisy variables, the pipeline evaluates three distinct feature selection methods:
     - *Filter Method (Variance Threshold)*: Evaluates intrinsic properties of features independently.
     - *Wrapper Method (RFE)*: Iteratively evaluates feature combinations.
     - *Embedded Method (Random Forest)*: Learns feature importance intrinsically during training.
   - **Balancing Robustness and Practicality:** To ensure optimal performance without overfitting, the script uses at least 30% of the dataset for evaluation. It then applies a 99% variance threshold check using PCA across the features selected by all three methods. It dynamically selects the method that requires the fewest Principal Components to satisfy the 99% variance threshold. This guarantees we pick the most practical (compact) yet robust set of features.
   - **Dimensionality Reduction (PCA):** Finally, Principal Component Analysis (PCA) is applied to the dynamically selected features to project the data into a lower-dimensional space, removing multicollinearity while strictly preserving 99% of the original data's information.
5. **Automated Reporting:** Generates a comprehensive, downloadable HTML EDA report using `ydata-profiling`.

## Usage Instructions
1. Open the Jupyter Notebook / Colab environment.
2. Run the cells sequentially.
3. When prompted, upload your standard `.csv` file.
4. You will be prompted to enter the name of the **target variable** for predictive modeling.
5. Upon completion, the pipeline automatically downloads:
   - `EDA_Feature_Engineering_Report_of_[filename].html`: The comprehensive profiling report.
   - `Processed_Data_[filename].csv`: The cleaned, engineered, and PCA-reduced dataset ready for modeling.

## Requirements
- pandas
- numpy
- matplotlib
- seaborn
- scikit-learn
- ydata-profiling
"""

with open("README.md", "w") as f:
    f.write(readme_content)

display(Markdown(readme_content))
print("README.md generated and displayed above.\n")

# =====================================================================
# STEP 1: Upload File and Setup
# =====================================================================
print("--- Step 1: Data Upload ---")
print("Please upload your dataset (CSV format):")
uploaded = files.upload()

if len(uploaded) > 0:
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
    print(f"\nSuccessfully loaded: {filename}")
    print(f"Dataset shape: {df.shape[0]} rows and {df.shape[1]} columns.")
else:
    print("No file uploaded. Please run the cell again and upload a file.")
    raise SystemExit("Execution stopped as no file was uploaded.")

print(f"\nAvailable columns:\n{df.columns.tolist()}")
target_col = input("\nEnter the name of the target variable column (leave blank to use the last column): ").strip()

if not target_col or target_col not in df.columns:
    target_col = df.columns[-1]
    print(f"Defaulting target column to: '{target_col}'\n")
else:
    print(f"Target column set to: '{target_col}'\n")

# Main pipeline wrapped in a function to execute after widget selection
def run_pipeline_initial(df_selected, target_col):
    numeric_cols = df_selected.select_dtypes(include=['number']).columns.tolist()
    categorical_cols = df_selected.select_dtypes(exclude=['number']).columns.tolist()

    # Remove target_col from these lists for feature-specific operations
    if target_col in numeric_cols:
        numeric_cols.remove(target_col)
    if target_col in categorical_cols:
        categorical_cols.remove(target_col)

    print(f"\nNumeric columns remaining: {len(numeric_cols)}")
    print(f"Categorical columns remaining: {len(categorical_cols)}")

    # =====================================================================
    # STEP 2: Clean Data (Nulls, Duplicates, and Outliers)
    # =====================================================================
    print("\n--- Step 2: Data Cleaning ---")
    df_clean = df_selected.copy()

    # Track cleaning stats
    initial_rows = df_clean.shape[0]
    initial_nulls = df_clean.isnull().sum().sum()

    # Drop Duplicates (applies to entire row, including target)
    df_clean = df_clean.drop_duplicates()
    duplicates_removed = initial_rows - df_clean.shape[0]

    # Handle Nulls for FEATURES (target handled separately if necessary)
    for col in numeric_cols:
        if df_clean[col].isnull().sum() > 0:
            df_clean[col].fillna(df_clean[col].median(), inplace=True)

    for col in categorical_cols:
        if df_clean[col].isnull().sum() > 0:
            df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

    # Handle Nulls for TARGET COLUMN (if any)
    if target_col in df_selected.columns and df_clean[target_col].isnull().sum() > 0:
        target_nulls_before_handling = df_clean[target_col].isnull().sum()
        if df_selected[target_col].nunique() < 20: # Treat as categorical for null handling logic
            df_clean.dropna(subset=[target_col], inplace=True)
            print(f"Dropped {target_nulls_before_handling} rows with missing values in the target column '{target_col}' to preserve class integrity.")
        else: # Treat as numeric for null handling logic
            df_clean[target_col].fillna(df_clean[col].median(), inplace=True)
            print(f"Imputed {target_nulls_before_handling} missing values in the numeric target column '{target_col}' with its median.")


    # Handle Outliers using IQR method (Capping) for FEATURES ONLY
    outliers_capped = 0
    for col in numeric_cols: # Only iterate through actual feature numeric_cols
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers_capped += ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()
        df_clean[col] = np.clip(df_clean[col], lower_bound, upper_bound)

    print("\n--- Data Cleaning Summary Output ---")
    print(f"1. Duplicates Removed: {duplicates_removed}")
    print(f"2. Null Values Imputed for Features: {initial_nulls - df_clean[target_col].isnull().sum()} (Median for numeric, Mode for categorical)")
    print(f"3. Outliers Capped for Features: {outliers_capped} (Using IQR boundaries)")
    print("------------------------------------\n")

    # Re-evaluate numeric_cols and categorical_cols after cleaning as target_col might have been removed
    numeric_cols_after_cleaning = df_clean.select_dtypes(include=['number']).columns.tolist()
    categorical_cols_after_cleaning = df_clean.select_dtypes(exclude=['number']).columns.tolist()
    if target_col in numeric_cols_after_cleaning:
        numeric_cols_after_cleaning.remove(target_col)
    if target_col in categorical_cols_after_cleaning:
        categorical_cols_after_cleaning.remove(target_col)


    # =====================================================================
    # STEP 3: Engineer Features (Scaling, Encoding, Binning)
    # =====================================================================
    print("--- Step 3: Feature Engineering ---")
    df_engineered = df_clean.copy()

    # Tracking applied engineering
    encoded_features = []
    scaled_features = []
    binned_features = []

    # Encoding Categorical Variables
    le = LabelEncoder()
    for col in categorical_cols_after_cleaning: # Use updated list
        df_engineered[col] = le.fit_transform(df_engineered[col].astype(str))
        encoded_features.append(col)
    print(f"Categorical variables encoded to numeric labels: {encoded_features}")

    # Binning: Create a binned version of the first numeric feature
    if len(numeric_cols_after_cleaning) > 0: # Use updated list
        first_num_col = numeric_cols_after_cleaning[0]
        est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
        df_engineered[f'{first_num_col}_binned'] = est.fit_transform(df_engineered[[first_num_col]])
        binned_features.append(f'{first_num_col}_binned')
        print(f"Created a binned feature: '{first_num_col}_binned' (Low, Medium, High categories).")

    # Scaling Numeric Features
    if numeric_cols_after_cleaning: # Use updated list
        scaler = StandardScaler()
        df_engineered[numeric_cols_after_cleaning] = scaler.fit_transform(df_engineered[numeric_cols_after_cleaning])
        scaled_features = numeric_cols_after_cleaning.copy()
        print(f"Numeric features standard scaled (mean=0, variance=1): {scaled_features}\n")

    # =====================================================================
    # STEP 4: Applied EDA
    # =====================================================================
    print("--- Step 4: Applied EDA ---")
    plt.figure(figsize=(10, 8))
    corr_matrix = df_engineered.corr(numeric_only=True)
    sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', linewidths=0.5)
    plt.title('Correlation Heatmap of Features')
    plt.tight_layout()
    plt.show()

    num_plots = min(len(numeric_cols_after_cleaning), 4)
    if num_plots > 0:
        fig, axes = plt.subplots(1, num_plots, figsize=(15, 4))
        if num_plots == 1: axes = [axes]
        for i in range(num_plots):
            sns.histplot(df_clean[numeric_cols_after_cleaning[i]], kde=True, ax=axes[i], color='skyblue')
            axes[i].set_title(f'Distribution: {numeric_cols_after_cleaning[i]}')
        plt.tight_layout()
        plt.show()

    # =====================================================================
    # STEP 5: Feature Selection & Evaluation (Balancing Practicality/Robustness)
    # =====================================================================
    print("\n--- Step 5: Feature Selection ---")
    X = df_engineered.drop(columns=[target_col])
    y = df_engineered[target_col]

    # Use at least 30% of data for feature selection
    sample_size = max(int(X.shape[0] * 0.30), min(20000, X.shape[0]))
    print(f"Using {sample_size} rows for feature selection evaluation (>= 30% of data)...")

    sample_indices = np.random.choice(X.shape[0], sample_size, replace=False)
    X_eval = X.iloc[sample_indices]
    y_eval = y.iloc[sample_indices]

    is_classification = y_eval.nunique() < 20
    print(f"Target Variable Identified: '{target_col}'")
    print(f"Task Type: {'Classification' if is_classification else 'Regression'}\n")

    # 1. Filter Method
    selector_filter = VarianceThreshold(threshold=0.01)
    selector_filter.fit(X_eval)
    features_filter = X.columns[selector_filter.get_support()]

    if is_classification:
        model = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
    else:
        model = RandomForestRegressor(n_estimators=50, random_state=42, n_jobs=-1)

    # 2. Wrapper Method
    rfe = RFE(estimator=model, n_features_to_select=max(1, X.shape[1]//2), step=0.1)
    rfe.fit(X_eval, y_eval)
    features_wrapper = X.columns[rfe.support_]

    # 3. Embedded Method
    model.fit(X_eval, y_eval)
    selector_embedded = SelectFromModel(model, prefit=True)
    features_embedded = X.columns[selector_embedded.get_support()]

    # Extract Feature Importances
    feature_weights = {}
    if hasattr(model, 'feature_importances_'):
        print("\n--- Feature Importances from Embedded Method (Random Forest) ---")
        feature_importances = pd.Series(model.feature_importances_, index=X_eval.columns)
        display(feature_importances.sort_values(ascending=False).to_frame(name='Importance'))
        print("------------------------------------------------------------------")
        feature_weights = feature_importances.to_dict()
    elif hasattr(model, 'coef_'):
        feature_weights = dict(zip(X_eval.columns, model.coef_[0] if is_classification else model.coef_))


    print("Narrative: Evaluating the 3 feature selection methods to balance robustness and practicality.")
    print("We apply PCA to the features selected by each method to see which provides the most compact representation that satisfies 99% variance:\n")

    methods_dict = {
        'Filter': features_filter,
        'Wrapper': features_wrapper,
        'Embedded': features_embedded
    }

    method_summaries_html_list = []
    for name, feats in methods_dict.items():
        if len(feats) == 0:
            comps = 0 # No components if no features
        else:
            pca_test = PCA(n_components=0.99, random_state=42)
            pca_test.fit(X_eval[feats])
            comps = pca_test.n_components_
        print(f" - {name} Method: Retained {len(feats)} features -> Requires {comps} PCA components to hit 99% variance.")
        method_summaries_html_list.append(f"<li><b>{name} Method:</b> Retained {len(feats)} features. Required {comps} PCA components to capture 99% variance.</li>")

    method_summaries_html = "\n                    ".join(method_summaries_html_list)

    # Now display the widget for the user to choose the method
    feature_method_choice_dropdown = widgets.Dropdown(
        options=['Filter', 'Wrapper', 'Embedded'],
        value='Filter', # Default selection
        description='Choose Method:',
        disabled=False,
    )

    continue_button = widgets.Button(description="Continue with Selected Method", button_style='success')
    choice_ui = widgets.VBox([feature_method_choice_dropdown, continue_button])
    display(choice_ui)

    # Pass necessary data to the next function using a lambda function with fixed arguments
    # Store important variables in global context if needed for the callback
    global _df_engineered, _X_original, _y_original, _target_col, _methods_dict, _method_summaries_html_list, _filename, _duplicates_removed, _initial_nulls, _outliers_capped
    global _encoded_features, _scaled_features, _binned_features, _feature_weights
    _df_engineered = df_engineered
    _X_original = X
    _y_original = y
    _target_col = target_col
    _methods_dict = methods_dict
    _method_summaries_html_list = method_summaries_html_list
    _filename = filename
    _duplicates_removed = duplicates_removed
    _initial_nulls = initial_nulls
    _outliers_capped = outliers_capped
    _encoded_features = encoded_features
    _scaled_features = scaled_features
    _binned_features = binned_features
    _feature_weights = feature_weights

    def on_continue_button_clicked(b):
        clear_output(wait=True)
        selected_feature_method = feature_method_choice_dropdown.value
        print(f"Continuing pipeline with the user-selected '{selected_feature_method}' method...")
        finalize_pipeline(selected_feature_method)

    continue_button.on_click(on_continue_button_clicked)

def finalize_pipeline(selected_feature_method):
    global _df_engineered, _X_original, _y_original, _target_col, _methods_dict, _method_summaries_html_list, _filename, _duplicates_removed, _initial_nulls, _outliers_capped
    global _encoded_features, _scaled_features, _binned_features, _feature_weights

    df_engineered = _df_engineered
    X = _X_original
    y = _y_original
    target_col = _target_col
    methods_dict = _methods_dict
    method_summaries_html_list = _method_summaries_html_list
    filename = _filename
    duplicates_removed = _duplicates_removed
    initial_nulls = _initial_nulls
    outliers_capped = _outliers_capped
    encoded_features = _encoded_features
    scaled_features = _scaled_features
    binned_features = _binned_features
    feature_weights = _feature_weights

    selected_method_pca_components = 0
    for name, feats in methods_dict.items():
        if name == selected_feature_method:
            if len(feats) == 0:
                selected_method_pca_components = 0
            else:
                pca_test = PCA(n_components=0.99, random_state=42)
                # Re-fit PCA on the full X if it was done on X_eval before
                pca_test.fit(X[feats])
                selected_method_pca_components = pca_test.n_components_
            break # Found the selected method

    # Finalize features based on the user's selection
    if selected_feature_method in methods_dict and len(methods_dict[selected_feature_method]) > 0:
        final_selected_features = methods_dict[selected_feature_method]
    else:
        print(f"WARNING: The selected feature method '{selected_feature_method}' resulted in no features or is invalid. Falling back to all features.")
        final_selected_features = X.columns.tolist()
        selected_method_pca_components = X.shape[1] # If all features are taken

    print(f"\nConclusion: The user-selected '{selected_feature_method}' method is being used.")
    print(f"It retained {len(final_selected_features)} features and requires {selected_method_pca_components} PCA components to successfully capture 99% of the data's variance.")

    X_selected = X[final_selected_features]

    print("\n--- Final Selected Features ---")
    for idx, feature in enumerate(final_selected_features, 1):
        print(f"{idx}. {feature}")
    print("-------------------------------")

    # =====================================================================
    # STEP 6: Dimensionality Reduction (PCA)
    # =====================================================================
    print("\n--- Step 6: Dimensionality Reduction (PCA) ---")
    print("Narrative: Dimensionality reduction is applied to remove multicollinearity and compress the feature space.")
    print(f"We apply PCA strictly on the {len(final_selected_features)} robust features selected above to capture 99% variance.")

    pca = PCA(n_components=0.99, random_state=42)
    X_pca = pca.fit_transform(X_selected)

    print(f"\nOriginal feature count (after selection): {X_selected.shape[1]}")
    print(f"PCA reduced feature count (explaining 99% variance): {X_pca.shape[1]}")

    plt.figure(figsize=(8, 5))
    plt.plot(np.cumsum(pca.explained_variance_ratio_), marker='o', linestyle='--', color='purple')
    plt.title('PCA - Cumulative Explained Variance')
    plt.xlabel('Number of Components')
    plt.ylabel('Cumulative Explained Variance')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    df_final = pd.DataFrame(X_pca, columns=[f'PC{i+1}' for i in range(X_pca.shape[1])])
    df_final['Target'] = y.values

    # =====================================================================
    # STEP 7: Output & Report
    # =====================================================================
    print("\n--- Step 7: Output & Downloadable Report ---")
    base_name = os.path.splitext(filename)[0]
    report_name = f"EDA_Feature_Engineering_Report_of_{base_name}.html"
    csv_name = f"Processed_Data_{base_name}.csv"

    print("Generating comprehensive EDA report (this may take a minute)...")
    profile = ProfileReport(df_engineered, title=f"EDA & Feature Eng Report: {base_name}", explorative=True) # Use df_engineered here, not df_clean
    html_content = profile.to_html()

    # Add this line to recreate the string from the list
    method_summaries_html = "\n                    ".join(method_summaries_html_list)

    # Prepare Feature Weights HTML
    weights_html = "<ul>"
    if feature_weights:
        for f in final_selected_features:
            weight = feature_weights.get(f, 0.0)
            polarity = "Positive" if weight >= 0 else "Negative"
            weights_html += f"<li><b>{f}</b>: Magnitude = {abs(weight):.4f}, Polarity = {polarity}</li>"
    else:
        weights_html += "<li>No explicit weights/importances available for the selected model.</li>"
    weights_html += "</ul>"

    # Create a comprehensive HTML summary for the Feature Engineering
    fe_summary_html = f"""
    <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f8f9fa; margin: 20px; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h2 style="color: #2c3e50; margin-top: 0;">Comprehensive Feature Engineering Summary</h2>
        <h4 style="color: #34495e;">1. Data Selection & Preprocessing</h4>
        <ul>
            <li><b>Target Variable:</b> {target_col}</li>
            <li><b>User-Selected Features ({len(X.columns)}):</b> {', '.join(X.columns)}</li>
            <li><b>Duplicates Removed:</b> {duplicates_removed} rows</li>
            <li><b>Null Values Imputed:</b> {initial_nulls} values</li>
            <li><b>Outliers Capped:</b> {outliers_capped} values (IQR Method)</li>
        </ul>
        <h4 style="color: #34495e;">2. Feature Engineering Applied</h4>
        <ul>
            <li><b>Scaled Features (StandardScaler):</b> {', '.join(scaled_features) if scaled_features else 'None'}</li>
            <li><b>Encoded Features (LabelEncoder):</b> {', '.join(encoded_features) if encoded_features else 'None'}</li>
            <li><b>Binned Features:</b> {', '.join(binned_features) if binned_features else 'None'}</li>
            <li><b>Domain-derived features:</b> Included automatically via binning if applicable.</li>
        </ul>
        <h4 style="color: #34495e;">3. Final Selected Features & Their Weights</h4>
        <p>The following features were finally selected, alongside their importance/weight from the embedded model evaluation.</p>
        {weights_html}
        <h4 style="color: #34495e;">4. Feature Selection & Dimensionality Reduction</h4>
        <ul>
            <li><b>Method Evaluation Results:</b>
                <ul>
                    {method_summaries_html}
                </ul>
            </li>
            <li><b>Selection Rationale:</b> The <b>{selected_feature_method}</b> method was chosen by the user. It retained {len(final_selected_features)} features and requires {selected_method_pca_components} PCA components to successfully capture 99% of the data's variance.</li>
            <li><b>Dimensionality Reduction:</b> Extracted <b>{pca.n_components_}</b> PCA components capturing 99% of original variance.</li>
        </ul>
        <hr style="border: 1px solid #ccc; margin: 20px 0;">
        <p style="margin-bottom: 0;"><i>Note: The automated EDA report below reflects the cleaned dataset prior to PCA compression.</i></p>
    </div>
    """

    # Inject the Feature Engineering Summary into the top of the HTML report
    if '<body>' in html_content:
        html_content = html_content.replace('<body>', f'<body>\n{fe_summary_html}', 1)
    else:
        html_content = fe_summary_html + html_content

    with open(report_name, "w", encoding="utf-8") as f:
        f.write(html_content)

    print("\nDownloads are starting...")
    files.download(report_name) # Always download the EDA report

    if df_final['Target'].nunique() < 2:
        print("\nWARNING: The target variable in the processed dataset only contains 1 class after feature engineering.")
        print("A processed CSV will not be generated as it's not suitable for predictive modeling.")
        print("Please review your original dataset or the data cleaning steps (especially duplicate removal) and target variable handling,")
        print("to ensure the minority class wasn't lost during preprocessing.")
        print("EDA Report downloaded. Process complete.")
    else:
        df_final.to_csv(csv_name, index=False)
        files.download(csv_name) # Only download the processed CSV if it's usable
        print("EDA Report and Processed Data downloaded. Process complete!")


print("\n=====================================================================")
print("STEP 1.5: Variable Selection")
print("=====================================================================")
print("Please check your data dictionary to know which variables are relevant.")
print("Tick the boxes below to INCLUDE variables in the analysis (Steps 2 onwards):")

checkboxes = []
for col in df.columns:
    if col != target_col:
        cb = widgets.Checkbox(value=True, description=col, indent=False)
        checkboxes.append(cb)

run_button = widgets.Button(description="Run Pipeline (Evaluate Feature Methods)", button_style='success')
ui = widgets.VBox(checkboxes + [run_button])
display(ui)

def on_initial_run_button_clicked(b):
    clear_output(wait=True)
    selected_cols = [cb.description for cb in checkboxes if cb.value]
    selected_cols.append(target_col)
    df_selected = df[selected_cols].copy()
    print(f"Continuing pipeline with {len(selected_cols)} selected columns...")
    run_pipeline_initial(df_selected, target_col)

run_button.on_click(on_initial_run_button_clicked)