# -*- coding: utf-8 -*-
"""OutlierAnalysisAndDataDemographics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQVfs6LLpQFJdkFUREa2oD_lyOLQGQOW
"""

"""
README: Data Quality Analysis Tool

AUTHOR: Gerand Boy O. Elinzano
Date: [date created]
Version: v1.0
Version Description: Initial Release
Remarks: Created via Google Collab

Libraries Needed
This script relies on the following Python libraries:
* pandas: For data manipulation, reading the CSV, and dataframe operations.
* numpy: For numerical operations.
* matplotlib & seaborn: For generating data visualizations (boxplots and histograms).
* scipy: For statistical functions, specifically calculating Z-scores.
* google.colab: For the file upload and download interface in Google Colab.
* io & base64: For handling byte streams and embedding the matplotlib plots as base64 images directly into the HTML.
* IPython.display: For displaying HTML outputs directly within the Colab cell outputs.

Main Function
* detect_outliers_html(df): This is the core helper function. It iterates through all numerical columns in the provided pandas DataFrame (df). For each column, it calculates the number of outliers using three different statistical methods:
    1. Z-Score
    2. IQR (Interquartile Range)
    3. Modified Z-Score

    It generates a boxplot and a distribution plot (histogram with KDE) for each column, converts these plots to base64 images, and compiles everything into a formatted HTML string containing both the plots and a summary table.

Needed Input
* A CSV File: Upon running the script, a prompt will appear asking you to upload a file. You must provide a dataset in .csv format.

Output
* analysis_report.html: The script generates and automatically downloads a standalone HTML report. This report includes:
    * A header and introduction stating the name of the analyzed file.
    * Data previews showing the first 20 and last 20 rows of your dataset.
    * An analysis of Missing Values.
    * The total count of Duplicate Values.
    * An Outlier Analysis section featuring summary tables and interactive visualizations for all numerical data.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import io
import base64
from scipy import stats
from IPython.display import display, HTML

def detect_outliers_html(df):
    numeric_cols = df.select_dtypes(include=[np.number]).columns

    if len(numeric_cols) == 0:
        return "<p>No numerical columns found to analyze for outliers.</p>"

    outlier_summary = []
    html_output = ""

    for col in numeric_cols:
        # Drop missing values for calculations
        col_data = df[col].dropna()

        if len(col_data) == 0:
            continue

        # 1. Z-Score
        z_scores = np.abs(stats.zscore(col_data))
        z_outliers = col_data[z_scores > 3]

        # 2. IQR
        Q1 = col_data.quantile(0.25)
        Q3 = col_data.quantile(0.75)
        IQR = Q3 - Q1
        iqr_outliers = col_data[(col_data < (Q1 - 1.5 * IQR)) | (col_data > (Q3 + 1.5 * IQR))]

        # 3. Modified Z-Score
        median = col_data.median()
        mad = np.median(np.abs(col_data - median))
        if mad == 0:
            mod_z_count = "N/A (MAD=0)"
        else:
            mod_z_scores = 0.6745 * (col_data - median) / mad
            mod_z_outliers = col_data[np.abs(mod_z_scores) > 3.5]
            mod_z_count = len(mod_z_outliers)

        outlier_summary.append({
            'Column': col,
            'Z-Score Outliers': len(z_outliers),
            'IQR Outliers': len(iqr_outliers),
            'Modified Z-Score Outliers': mod_z_count
        })

        # Visualization
        html_output += f"<h4>Distribution and Boxplot for: {col}</h4>\n"
        fig, ax = plt.subplots(1, 2, figsize=(12, 4))

        # Boxplot
        sns.boxplot(x=col_data, ax=ax[0])
        ax[0].set_title(f'Boxplot of {col}')

        # Histogram with KDE
        sns.histplot(col_data, kde=True, ax=ax[1])
        ax[1].set_title(f'Distribution of {col}')

        plt.tight_layout()

        # Save figure to base64 string to embed in HTML
        buf = io.BytesIO()
        plt.savefig(buf, format='png')
        plt.close(fig)
        img_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')
        html_output += f'<img src="data:image/png;base64,{img_base64}" alt="{col} plots" style="max-width:100%;height:auto;"/><br>\n'

    if outlier_summary:
        summary_df = pd.DataFrame(outlier_summary)
        html_output += "<h3>Outlier Summary Table</h3>\n"
        html_output += summary_df.to_html(index=False, classes='table table-striped', border=1)

    return html_output

# 1. Upload facility
display(HTML("<h3>Please upload your CSV file:</h3>"))
try:
    uploaded = files.upload()
except TypeError:
    uploaded = None
    display(HTML("<p>Upload cancelled or failed. Please run the cell again.</p>"))
except Exception as e:
    uploaded = None
    display(HTML(f"<p>An unexpected error occurred during upload: {e}</p>"))

if uploaded:
    file_name = list(uploaded.keys())[0]

    # Read the CSV file
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))

    # Build HTML Content
    html_content = "<html><head><title>Analysis Report</title>"
    html_content += "<style>body{font-family: Arial, sans-serif; margin: 20px;} table{border-collapse: collapse; margin-bottom: 20px; width: 100%;} th, td{border: 1px solid #ddd; padding: 8px; text-align: left;} th{background-color: #f2f2f2;} h1, h2, h3{color: #333;}</style>"
    html_content += "</head><body>"

    # Header and Intro
    html_content += "<h1>Outlier, Missing Value, and Duplicate</h1>\n"
    html_content += f"<p>This site shows the 'Outlier, Missing Value, and Duplicate' of '{file_name}'.</p>\n"

    # First 20 Rows
    html_content += "<h2>First 20 Rows</h2>\n"
    html_content += df.head(20).to_html(classes='table table-striped', border=1)

    # Last 20 Rows
    html_content += "<h2>Last 20 Rows</h2>\n"
    html_content += df.tail(20).to_html(classes='table table-striped', border=1)

    # 2. Determine missing values
    html_content += "<h2>Missing Values</h2>\n"
    missing = df.isnull().sum()
    missing_df = missing[missing > 0].reset_index()
    missing_df.columns = ['Column', 'Missing Count']

    if len(missing_df) > 0:
        html_content += missing_df.to_html(index=False, classes='table table-striped', border=1)
    else:
        html_content += "<p>No missing values found.</p>\n"

    # 3. Determine duplicate values
    html_content += "<h2>Duplicate Values</h2>\n"
    duplicates = df.duplicated().sum()
    html_content += f"<p>Total duplicate rows: <b>{duplicates}</b></p>\n"

    # 4. Outlier Analysis & Visualization
    html_content += "<h2>Outlier Analysis</h2>\n"
    html_content += detect_outliers_html(df)

    html_content += "</body></html>"

    # Save the HTML output to a file
    output_filename = "analysis_report.html"
    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(html_content)

    display(HTML(f"<p>Analysis complete! A downloadable file <b>{output_filename}</b> has been generated.</p>"))

    # Trigger automatic download
    files.download(output_filename)
else:
    display(HTML("<p>No valid file was processed.</p>"))