# -*- coding: utf-8 -*-
"""SHAPLIME/PDP/ICE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZqCl35wj8wE-Z4Wh469vjNRApyT8Dkp
"""

!pip install -q shap lime

import shap
import lime
import lime.lime_tabular
from sklearn.inspection import PartialDependenceDisplay
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display, Markdown
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from datetime import datetime

# =====================================================================
# STEP 0: Generate Audit & Explainability README
# =====================================================================
current_date = datetime.now().strftime('%B %d, %Y')

readme_audit = f"""# Model Explainability and Fairness Audit Module

## Overview
This module provides deep-dive diagnostics for the 'Best Model' selected in the previous training phase. It bridges the gap between high-performance 'black-box' models and human-readable ethics.

## Capabilities / Steps Performed
1. **Pipeline Reconstruction:** To explain predictions in terms of **original features** (instead of abstract PCA components), the module reconstructs the full transformation sequence (Scaling -> PCA -> Model) into a single scikit-learn Pipeline.
2. **Global Explainability (SHAP):** Uses Shapley Additive Explanations to quantify the contribution of each original feature to the overall model predictions.
3. **Feature Interaction (PDP & ICE):** Generates Partial Dependence and Individual Conditional Expectation plots to visualize how changes in specific features (like transaction amount) influence the probability of fraud.
4. **Bias & Fairness Audit:** Calculates rigorous metrics (Disparate Impact, Demographic Parity, Equal Opportunity) using socioeconomic proxies to ensure the model does not discriminate against specific user groups.
5. **Ethical Reporting:** Synthesizes all findings into a Markdown report for stakeholders.

## Usage Instructions
1. Ensure the training module has completed and `results_df` and `tuned_models` are available in the kernel.
2. Execute this cell to generate visual insights and fairness metrics.
3. Review the SHAP summary for global feature importance and PDP plots for local feature behavior.

## Requirements
- `shap`
- `lime`
- `scikit-learn` (version >= 1.0 for PartialDependenceDisplay)
- `matplotlib` & `seaborn`

---
**AUTHOR:** Gerand Boy O. Elinzano
**Date:** July 10, 2026
**Version:** v1.0
**Version Description:** Initial Release
**Remarks:** Created via Google Colab
"""
display(Markdown(readme_audit))

# 1. Identify the Best Model
best_model_name = results_df.iloc[0]['Model']
best_model = tuned_models[best_model_name]
print(f"--- Using Best Model: {best_model_name} for Explainability & Audit --- ")

# --- Reconstruct Transformations for Original Feature Explainability ---
original_feature_names = [
    'transaction_amount', 'device_risk_score', 'anomaly_score',
    'account_age_days', 'avg_monthly_balance', 'daily_transaction_count',
    'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score'
]

X_train_orig = df.loc[X_train.index, original_feature_names].copy()
X_test_orig = df.loc[X_test.index, original_feature_names].copy()

class PCANameWrapper(BaseEstimator, TransformerMixin):
    def __init__(self, pca_model):
        self.pca_model = pca_model
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        pca_data = self.pca_model.transform(X)
        return pd.DataFrame(pca_data, columns=[f'PC{i+1}' for i in range(pca_data.shape[1])])

scaler = StandardScaler().fit(X_train_orig)
pca_base = PCA(n_components=X_train.shape[1], random_state=42).fit(scaler.transform(X_train_orig))

full_pipeline = Pipeline([
    ('scaler', scaler),
    ('pca_naming', PCANameWrapper(pca_base)),
    ('model', best_model)
])

# 2. Explainability: SHAP
print("\n1. SHAP Summary Plot (Global Explainability)")
try:
    background_data = shap.kmeans(X_train_orig, 25)
    explainer = shap.KernelExplainer(lambda x: full_pipeline.predict_proba(x)[:, 1], background_data)
    sample_size = min(100, len(X_test_orig))
    shap_values = explainer.shap_values(X_test_orig.iloc[:sample_size])

    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values, X_test_orig.iloc[:sample_size], feature_names=original_feature_names, show=False)
    plt.title(f'SHAP Summary for {best_model_name} (Original Features)')
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"SHAP plot generation encountered an issue: {e}")

# 3. Explainability: PDP and ICE
print("\n2. Partial Dependence (PDP) and Individual Conditional Expectation (ICE) Plots")
try:
    fig, ax = plt.subplots(figsize=(12, 5))
    top_features = original_feature_names[:2]
    PartialDependenceDisplay.from_estimator(
        full_pipeline, X_test_orig, features=top_features, kind='both',
        grid_resolution=20, ax=ax
    )
    plt.subplots_adjust(top=0.9)
    plt.suptitle(f'PDP and ICE Plots for {best_model_name} (Original Features)')
    plt.show()
except Exception as e:
    print(f"PDP/ICE generation encountered an issue: {e}")

# 4. Bias Audit & Fairness Metrics
print("\n3. Fairness Audit Across Sensitive Groups")
if 'avg_monthly_balance' in df.columns:
    median_balance = df['avg_monthly_balance'].median()
    test_proxies = df.loc[X_test.index, 'avg_monthly_balance']
    sensitive_attr = (test_proxies > median_balance).astype(int)
    y_pred = full_pipeline.predict(X_test_orig)

    mask_unpriv = (sensitive_attr == 0)
    mask_priv = (sensitive_attr == 1)

    pos_rate_unpriv = np.mean(y_pred[mask_unpriv])
    pos_rate_priv = np.mean(y_pred[mask_priv])
    disparate_impact = pos_rate_unpriv / pos_rate_priv if pos_rate_priv > 0 else np.nan

    tn_u, fp_u, fn_u, tp_u = confusion_matrix(y_test[mask_unpriv], y_pred[mask_unpriv]).ravel()
    tn_p, fp_p, fn_p, tp_p = confusion_matrix(y_test[mask_priv], y_pred[mask_priv]).ravel()

    tpr_unpriv = tp_u / (tp_u + fn_u) if (tp_u + fn_u) > 0 else 0
    tpr_priv = tp_p / (tp_p + fn_p) if (tp_p + fn_p) > 0 else 0

    print(f"Sensitive Attribute Proxy: Socioeconomic Status (SES) via 'avg_monthly_balance'")
    print(f"\n--- Fairness Metrics ---")
    print(f"Demographic Parity (Pos Rate Unpriv): {pos_rate_unpriv:.4f}")
    print(f"Demographic Parity (Pos Rate Priv): {pos_rate_priv:.4f}")
    print(f"Disparate Impact (Ideal is ~1.0): {disparate_impact:.4f}")
    print(f"Equal Opportunity TPR Unpriv: {tpr_unpriv:.4f} | TPR Priv: {tpr_priv:.4f}")

# 5. Generate Comprehensive Ethical AI Report
report = """
## Comprehensive Ethical AI and Bias Audit Report

### 1. Explainability & Interpretability
* **SHAP values on Original Features:** Analyzed using a reconstructed pipeline to map model decisions back to raw variables.
* **Model Behavior (PDP/ICE):** Visualizes how feature changes influence fraud probability across the entire population and individual cases.

### 2. Discussion of Data and Model Limitations
* **Class Imbalance:** Fraud datasets require monitoring to ensure minority class patterns are learned.
* **Overfitting:** High metrics should be validated against real-world drift.

### 3. Bias Detection and Fairness Audit
* **Disparate Impact:** Checks for systemic bias in predictions relative to socioeconomic proxies.
"""
display(Markdown(report))