# -*- coding: utf-8 -*-
"""SupervisedLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9nO4Oj-SKc4D0x68bQyD4dC6sQjwfzd
"""

"""
## Overview
This repository contains a reproducible, dynamic Python pipeline built in Google Colab that performs supervised machine learning by training and evaluating various classification models, including Logistic Regression, Decision Tree, Random Forest, XGBoost, and Support Vector Machine (SVM), on an uploaded CSV dataset.

## Details
AUTHOR: Gerand Boy O. Elinzano
Date: July 9, 2026
Version: v1.0
Version Description: Initial Release
Remarks: Created via Google Collab

## Capabilities / Steps Performed
1.  **Data Loading and Target Identification**: The pipeline prompts the user to upload a processed dataset (CSV format). It then automatically identifies the target column, defaulting to 'Target' or the last column if 'Target' is not present.
2.  **Data Splitting**: The dataset is split into training (70%) and testing (30%) sets, ensuring stratification for balanced class distribution.
3.  **Model Initialization**: Five popular machine learning classification models are initialized: Logistic Regression, Decision Tree, Random Forest, XGBoost, and Support Vector Machine (SVM).
4.  **Hyperparameter Tuning and Training**: Each model undergoes hyperparameter tuning using `GridSearchCV` with 3-fold cross-validation. The tuning optimizes for ROC-AUC (for binary classification) or Accuracy (for multi-class classification).
5.  **Model Evaluation**: Trained models are evaluated on the test set using a comprehensive set of metrics including Accuracy, Precision, Recall, F1-Score, ROC-AUC, and R-Squared.
6.  **Visualizations**: The pipeline generates visualizations for each model, including ROC Curves to assess classifier performance and scatter plots of predictions against actual values (using jitter for clarity).
7.  **Model Performance Comparison**: A comparative table summarizing the performance of all trained models is displayed, sorted by ROC-AUC or Accuracy.
8.  **Reproducibility**: All trained models, along with the training configuration and evaluation results, are saved to a `models/` directory for reproducibility and future use.

## Usage Instructions
1. Open the Jupyter Notebook / Colab environment.
2. Run the cells sequentially.
3. When prompted, upload your pre-processed `.csv` file. **Note: This pipeline expects a pre-processed dataset ready for direct model training. If you need code for data preprocessing and feature engineering, please refer to `datapreprocessingedaandfeatureengineering.py`.**
4. The pipeline will automatically identify the target column from your uploaded data.
5. Upon completion, the pipeline will save the following artifacts to a local `models/` directory:
   - Trained machine learning models (e.g., `logistic_regression_model.joblib`).
   - A training configuration file (`training_config.json`).
   - Evaluation metrics in a CSV file (`evaluation_results.csv`).

## Requirements
- pandas
- numpy
- matplotlib
- seaborn
- scikit-learn
- xgboost
"""
import pandas as pd
import numpy as np
import time
import io
import os
import json
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from IPython.display import display
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, r2_score, roc_curve

# 1. Upload the dataset
print("Please upload your processed dataset (CSV format):")
uploaded = files.upload()

if not uploaded:
    raise FileNotFoundError("No file was uploaded. Please run the cell again and select a file.")

filename = list(uploaded.keys())[0]
print(f"\nLoading data from: {filename}\n")
df_model = pd.read_csv(io.BytesIO(uploaded[filename]))

# Fallback to the last column if 'Target' is not explicitly found
target_col = 'Target' if 'Target' in df_model.columns else df_model.columns[-1]

X = df_model.drop(columns=[target_col])
y = df_model[target_col]

# Quick check on target classes to avoid 1-class ValueError
if y.nunique() < 2:
    print("WARNING: The dataset only contains 1 class. Predictive models cannot be trained without at least 2 classes.")
    print("Please check the original data to ensure the minority class wasn't lost during preprocessing.")
else:
    # Ensure 100% of the dataset is used by removing sampling logic
    print(f"\nDataset contains {len(X)} rows. Using the entire dataset for training and evaluation...")

    # 3. Split the data into Training and Testing sets (70% train / 30% test)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    print(f"Training data shape: {X_train.shape[0]} rows (70%)")
    print(f"Testing data shape: {X_test.shape[0]} rows (30%)\n")

    # 4. Initialize the 5 models and their parameter grids for tuning
    models_and_params = {
        "Logistic Regression": {
            "model": LogisticRegression(random_state=42, max_iter=1000),
            "params": {'C': [0.1, 1, 10]}
        },
        "Decision Tree": {
            "model": DecisionTreeClassifier(random_state=42),
            "params": {'max_depth': [3, 5, 7]}
        },
        "Random Forest": {
            "model": RandomForestClassifier(random_state=42, n_estimators=100),
            "params": {'n_estimators': [50, 100], 'max_depth': [5, 10]}
        },
        "XGBoost": {
            "model": XGBClassifier(random_state=42, n_estimators=100, eval_metric='logloss', use_label_encoder=False),
            "params": {'n_estimators': [50, 100], 'learning_rate': [0.01, 0.1]}
        },
        "SVM": {
            "model": SVC(random_state=42, probability=True, max_iter=-1),
            "params": {'C': [0.1, 1], 'kernel': ['linear', 'rbf']}
        }
    }

    # Documenting the "epochs" / iterations / trees for the table
    epochs_mapping = {
        "Logistic Regression": "1000 (max_iter) - Tuned",
        "Decision Tree": "Tuned (max_depth)",
        "Random Forest": "Tuned (n_estimators, max_depth)",
        "XGBoost": "Tuned (n_estimators, learning_rate)",
        "SVM": "Tuned (C, kernel)"
    }

    results = []
    roc_data = {}
    tuned_models = {}

    print("Training and evaluating models with hyperparameter tuning...")
    # 5. Train and evaluate each model with GridSearchCV
    for name, mp in models_and_params.items():
        start_time = time.time()
        print(f" - Tuning and Training {name}...")

        grid_search = GridSearchCV(mp["model"], mp["params"], cv=3, scoring='roc_auc' if len(y.unique())==2 else 'accuracy', n_jobs=-1)
        grid_search.fit(X_train, y_train)

        model = grid_search.best_estimator_
        tuned_models[name] = model

        # Predict classes and probabilities
        y_pred = model.predict(X_test)

        # Multiclass vs Binary target handling
        num_classes = len(y.unique())
        avg_method = 'binary' if num_classes == 2 else 'macro'

        # Calculate baseline metrics
        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred, average=avg_method, zero_division=0)
        rec = recall_score(y_test, y_pred, average=avg_method, zero_division=0)
        f1 = f1_score(y_test, y_pred, average=avg_method, zero_division=0)

        # Adding R-squared as requested
        r2 = r2_score(y_test, y_pred)

        # Calculate ROC-AUC
        roc_auc = None
        try:
            if num_classes == 2:
                y_prob = model.predict_proba(X_test)[:, 1]
                roc_auc = roc_auc_score(y_test, y_prob)
                fpr, tpr, _ = roc_curve(y_test, y_prob)
                roc_data[name] = (fpr, tpr, roc_auc)
            else:
                y_prob = model.predict_proba(X_test)
                roc_auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
        except Exception as e:
            pass

        elapsed_time = time.time() - start_time

        # Store results
        res_dict = {
            "Model": name,
            "Epochs / Iterations": epochs_mapping[name],
            "Best Parameters": json.dumps(grid_search.best_params_),
            "Best CV Score": grid_search.best_score_,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1-Score": f1,
            "ROC-AUC": roc_auc,
            "R-Squared": r2,
            "Time (s)": round(elapsed_time, 2)
        }

        results.append(res_dict)

    # Visualizations Before Comparison Table
    print("\n=========================================")
    print("         Model Visualizations            ")
    print("=========================================")

    jitter = np.random.normal(0, 0.05, size=len(y_test))

    # Display separate graphs per algorithm
    for name, model in tuned_models.items():
        print(f"\n--- Visualizing: {name} ---")
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # 1. ROC Curve for the specific model
        if name in roc_data:
            fpr, tpr, auc_val = roc_data[name]
            axes[0].plot(fpr, tpr, lw=2, color='darkorange', label=f"AUC = {auc_val:.3f}")
            axes[0].plot([0, 1], [0, 1], color='gray', linestyle='--')
            axes[0].set_xlim([0.0, 1.0])
            axes[0].set_ylim([0.0, 1.05])
            axes[0].set_xlabel('False Positive Rate')
            axes[0].set_ylabel('True Positive Rate')
            axes[0].set_title(f'ROC Curve - {name}')
            axes[0].legend(loc="lower right")
            axes[0].grid(alpha=0.3)
        else:
            axes[0].text(0.5, 0.5, 'ROC Curve not available', ha='center', va='center')
            axes[0].set_title(f'ROC Curve - {name}')
            axes[0].axis('off')

        # 2. Scatter Plot for the specific model
        y_pred_model = model.predict(X_test)
        if X_test.shape[1] >= 1:
            scatter = axes[1].scatter(X_test.iloc[:, 0], y_test + jitter, c=y_pred_model, cmap='coolwarm', alpha=0.5, edgecolor='k')
            axes[1].set_xlabel(X_test.columns[0])
            axes[1].set_ylabel(f"True {target_col} (with jitter)")
            axes[1].set_title(f'Predictions Scatter - {name}')
            axes[1].set_yticks(ticks=np.unique(y_test))
            fig.colorbar(scatter, ax=axes[1], ticks=np.unique(y_pred_model), label='Predicted Class')
            axes[1].grid(alpha=0.3)
        else:
            axes[1].text(0.5, 0.5, 'Scatter Plot not available', ha='center', va='center')
            axes[1].axis('off')

        plt.tight_layout()
        plt.show()

    # 6. Display the comparison table
    if results:
        results_df = pd.DataFrame(results)

        # Sort by ROC-AUC (or Accuracy if ROC-AUC is not available)
        if results_df['ROC-AUC'].isnull().all():
            results_df = results_df.sort_values(by="Accuracy", ascending=False).reset_index(drop=True)
        else:
            results_df = results_df.sort_values(by="ROC-AUC", ascending=False).reset_index(drop=True)

        print("\n=========================================")
        print("       Model Performance Comparison      ")
        print("=========================================")
        # Select columns to apply the gradient to (excluding categorical or potentially empty columns)
        gradient_cols = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC', 'R-Squared', 'Best CV Score']

        display(results_df.style.background_gradient(cmap='Blues', subset=gradient_cols))

        # 7. Reproducibility: Save Models, Configs, and Artifacts
        model_dir = 'models'
        os.makedirs(model_dir, exist_ok=True)
        print(f"\nSaving trained models, configs, and artifacts to '{model_dir}/'...")

        # Save each trained model
        for name, model in tuned_models.items():
            model_filename = os.path.join(model_dir, f'{name.replace(" ", "_").lower()}_model.joblib')
            joblib.dump(model, model_filename)
            print(f"Saved {name} to {model_filename}")

        # Save configuration
        config_data = {
            "target_column": target_col,
            "test_size": 0.3,
            "random_state": 42,
            "models_trained": list(tuned_models.keys())
        }
        with open(os.path.join(model_dir, 'training_config.json'), 'w') as f:
            json.dump(config_data, f, indent=4)
        print(f"Saved training configuration to {os.path.join(model_dir, 'training_config.json')}")

        # Save artifacts (evaluation results)
        results_csv_path = os.path.join(model_dir, 'evaluation_results.csv')
        results_df.to_csv(results_csv_path, index=False)
        print(f"Saved evaluation metrics to {results_csv_path}")

        print("\nAll models, configs, and artifacts saved successfully.")